In [1]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
data=pd.read_csv("E:\\data science\\assiments\\15\\Fraud_check.csv")

In [3]:
data.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [4]:
data = pd.get_dummies(data, columns = ['Undergrad','Marital.Status','Urban'])

In [5]:
data.head()

Taxable.Income  City.Population  Work.Experience  Undergrad_NO  \
0           68833            50047               10             1   
1           33700           134075               18             0   
2           36925           160205               30             1   
3           50190           193264               15             0   
4           81002            27533               28             1   

   Undergrad_YES  Marital.Status_Divorced  Marital.Status_Married  \
0              0                        0                       0   
1              1                        1                       0   
2              0                        0                       1   
3              1                        0                       0   
4              0                        0                       1   

   Marital.Status_Single  Urban_NO  Urban_YES  
0                      1         0          1  
1                      0         0          1  
2                      0         0          1  
3                      1         0          1  
4                      0         1          0

In [6]:
data["TaxableIncome"]="good"
data.loc[data["Taxable.Income"]<= 30000,"TaxableIncome"]="risk"
data.drop(["Taxable.Income"],axis=1,inplace=True)

In [7]:
array=data.values

In [8]:
data.head()

City.Population  Work.Experience  Undergrad_NO  Undergrad_YES  \
0            50047               10             1              0   
1           134075               18             0              1   
2           160205               30             1              0   
3           193264               15             0              1   
4            27533               28             1              0   

   Marital.Status_Divorced  Marital.Status_Married  Marital.Status_Single  \
0                        0                       0                      1   
1                        1                       0                      0   
2                        0                       1                      0   
3                        0                       0                      1   
4                        0                       1                      0   

   Urban_NO  Urban_YES TaxableIncome  
0         0          1          good  
1         0          1          good  
2         0          1          good  
3         0          1          good  
4         1          0          good

In [9]:
x = array[:,0:9]
y = array[:,9]

### spliting the data

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, stratify = y)

### applying RF

In [20]:
num_trees = 100
max_features = 3
kfold = KFold(n_splits=10)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
model.fit(x_train,y_train)
acc = accuracy_score(y_test, pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, pred)

Accuracy = 72.5


array([[85, 10],
       [23,  2]], dtype=int64)

In [21]:
results

array([0.79166667, 0.75      , 0.79166667, 0.79166667, 0.66666667,
       0.77083333, 0.64583333, 0.6875    , 0.6875    , 0.625     ])

In [22]:
pred=model.predict(x_test)

In [23]:
pred

array(['good', 'good', 'good', 'good', 'risk', 'good', 'good', 'good',
       'good', 'good', 'good', 'risk', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'risk', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'risk', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'risk', 'risk',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'risk', 'risk',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'risk', 'good', 'risk', 'good', 'good', 'good', 'good',
       'good', 'good', 'risk', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
      

### actual value and predicted value

In [24]:
df=pd.DataFrame({"actual":y_test,"predicted":pred})

In [25]:
df

actual predicted
0     good      good
1     good      good
2     risk      good
3     good      good
4     good      risk
..     ...       ...
115   good      good
116   good      good
117   risk      risk
118   good      good
119   good      good

[120 rows x 2 columns]

In [30]:
column=data.columns
column

Index(['City.Population', 'Work.Experience', 'Undergrad_NO', 'Undergrad_YES',
       'Marital.Status_Divorced', 'Marital.Status_Married',
       'Marital.Status_Single', 'Urban_NO', 'Urban_YES', 'TaxableIncome'],
      dtype='object')

In [31]:
column=column.drop("TaxableIncome")

### feature importance

In [32]:
feature=model.feature_importances_
feature

array([0.51089751, 0.36386636, 0.01736157, 0.01574455, 0.01907954,
       0.01890223, 0.02075156, 0.01668672, 0.01670996])

In [33]:
df1=pd.DataFrame({"column":column,"importance":feature})
df1.sort_values("importance",ascending=False)

column  importance
0          City.Population    0.510898
1          Work.Experience    0.363866
6    Marital.Status_Single    0.020752
4  Marital.Status_Divorced    0.019080
5   Marital.Status_Married    0.018902
2             Undergrad_NO    0.017362
8                Urban_YES    0.016710
7                 Urban_NO    0.016687
3            Undergrad_YES    0.015745

##### city population have high importance